defmodule SertantaiHub.Repo.Migrations.AddNotificationResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:law_change_subscriptions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :organization_id,
        references(:organizations,
          column: :id,
          name: "law_change_subscriptions_organization_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "law_change_subscriptions_user_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:name, :text, null: false)
      add(:law_families, {:array, :text}, default: [])
      add(:geo_extent, {:array, :text}, default: [])
      add(:change_types, {:array, :text}, default: [])
      add(:keywords, {:array, :text}, default: [])
      add(:type_codes, {:array, :text}, default: [])
      add(:frequency, :text, null: false, default: "daily_digest")
      add(:delivery_methods, {:array, :text}, default: fragment("ARRAY['email']::text[]"))
      add(:enabled, :boolean, null: false, default: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:law_change_events, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :organization_id,
        references(:organizations,
          column: :id,
          name: "law_change_events_organization_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :subscription_id,
        references(:law_change_subscriptions,
          column: :id,
          name: "law_change_events_subscription_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:law_name, :text, null: false)
      add(:law_title, :text, null: false)
      add(:change_type, :text, null: false)
      add(:families, {:array, :text}, default: [])
      add(:summary, :text)
      add(:source_metadata, :map)
      add(:delivered_at, :utc_datetime)
      add(:batch_id, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    # Enable ElectricSQL sync (REPLICA IDENTITY required for logical replication)
    execute("ALTER TABLE law_change_subscriptions REPLICA IDENTITY FULL")
    execute("ALTER TABLE law_change_events REPLICA IDENTITY FULL")
  end

  def down do
    drop(constraint(:law_change_events, "law_change_events_organization_id_fkey"))

    drop(constraint(:law_change_events, "law_change_events_subscription_id_fkey"))

    drop(table(:law_change_events))

    drop(constraint(:law_change_subscriptions, "law_change_subscriptions_organization_id_fkey"))

    drop(constraint(:law_change_subscriptions, "law_change_subscriptions_user_id_fkey"))

    drop(table(:law_change_subscriptions))
  end
end
